-- Relational companion schema. Identity syntax may need adjustment for the
-- target database. The application currently executes sqlite_schema.sql.

CREATE TABLE locations (
    location_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city VARCHAR(100) NOT NULL,
    area VARCHAR(100) NOT NULL,
    address VARCHAR(255) NOT NULL
);

CREATE TABLE restaurants (
    restaurant_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_id INTEGER NOT NULL REFERENCES locations(location_id),
    name VARCHAR(150) NOT NULL,
    opening_date DATE,
    seating_capacity INTEGER CHECK (seating_capacity IS NULL OR seating_capacity >= 0)
);

CREATE TABLE menu_categories (
    category_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(500)
);

CREATE TABLE menu_items (
    menu_item_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id INTEGER NOT NULL REFERENCES restaurants(restaurant_id),
    category_id INTEGER NOT NULL REFERENCES menu_categories(category_id),
    name VARCHAR(150) NOT NULL,
    description VARCHAR(1000),
    base_price DECIMAL(12,2) NOT NULL CHECK (base_price >= 0),
    cost_price DECIMAL(12,2) NOT NULL CHECK (cost_price >= 0),
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE pricing_history (
    pricing_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menu_item_id INTEGER NOT NULL REFERENCES menu_items(menu_item_id),
    effective_from DATE NOT NULL,
    effective_to DATE,
    price DECIMAL(12,2) NOT NULL CHECK (price >= 0),
    cost_price DECIMAL(12,2) CHECK (cost_price IS NULL OR cost_price >= 0),
    reason VARCHAR(250),
    CHECK (effective_to IS NULL OR effective_to >= effective_from)
);

-- Deliberately pseudonymous profile attributes; do not add direct PII here.
CREATE TABLE customers (
    customer_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_id INTEGER REFERENCES locations(location_id),
    first_seen DATE,
    preferred_channel VARCHAR(80),
    preferred_category VARCHAR(100),
    customer_value_segment VARCHAR(80),
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE promotions (
    promotion_id VARCHAR(60) PRIMARY KEY,
    restaurant_id INTEGER REFERENCES restaurants(restaurant_id),
    menu_item_id INTEGER REFERENCES menu_items(menu_item_id),
    name VARCHAR(150) NOT NULL,
    description VARCHAR(500),
    discount_percentage DECIMAL(5,2) NOT NULL CHECK (discount_percentage BETWEEN 0 AND 100),
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CHECK (end_date >= start_date)
);

CREATE TABLE orders (
    order_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INTEGER REFERENCES customers(customer_id),
    restaurant_id INTEGER NOT NULL REFERENCES restaurants(restaurant_id),
    order_date TIMESTAMP NOT NULL,
    order_channel VARCHAR(80) NOT NULL,
    payment_method VARCHAR(80),
    order_status VARCHAR(20) NOT NULL CHECK (order_status IN ('Completed', 'Cancelled', 'Refunded')),
    subtotal DECIMAL(12,2) NOT NULL CHECK (subtotal >= 0),
    tax_amount DECIMAL(12,2) NOT NULL DEFAULT 0 CHECK (tax_amount >= 0),
    discount_amount DECIMAL(12,2) NOT NULL DEFAULT 0 CHECK (discount_amount >= 0),
    total_amount DECIMAL(12,2) NOT NULL CHECK (total_amount >= 0),
    promotion_id VARCHAR(60) REFERENCES promotions(promotion_id)
);

CREATE TABLE order_items (
    order_item_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INTEGER NOT NULL REFERENCES orders(order_id) ON DELETE CASCADE,
    menu_item_id INTEGER NOT NULL REFERENCES menu_items(menu_item_id),
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    unit_price DECIMAL(12,2) NOT NULL CHECK (unit_price >= 0),
    discount_amount DECIMAL(12,2) NOT NULL DEFAULT 0 CHECK (discount_amount >= 0),
    line_total DECIMAL(12,2) NOT NULL CHECK (line_total >= 0)
);

CREATE TABLE ratings (
    rating_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INTEGER REFERENCES customers(customer_id),
    order_id INTEGER REFERENCES orders(order_id),
    menu_item_id INTEGER NOT NULL REFERENCES menu_items(menu_item_id),
    rating_score INTEGER NOT NULL CHECK (rating_score BETWEEN 1 AND 5),
    review_text VARCHAR(2000),
    rating_date TIMESTAMP NOT NULL
);

CREATE TABLE inventory (
    inventory_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id INTEGER NOT NULL REFERENCES restaurants(restaurant_id),
    menu_item_id INTEGER NOT NULL REFERENCES menu_items(menu_item_id),
    stock_on_hand DECIMAL(12,3) NOT NULL CHECK (stock_on_hand >= 0),
    reorder_level DECIMAL(12,3) NOT NULL DEFAULT 0 CHECK (reorder_level >= 0),
    unit_cost DECIMAL(12,2) CHECK (unit_cost IS NULL OR unit_cost >= 0),
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (restaurant_id, menu_item_id)
);

CREATE TABLE wastage (
    wastage_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id INTEGER NOT NULL REFERENCES restaurants(restaurant_id),
    menu_item_id INTEGER NOT NULL REFERENCES menu_items(menu_item_id),
    quantity_wasted DECIMAL(12,3) NOT NULL CHECK (quantity_wasted > 0),
    wastage_cost DECIMAL(12,2) NOT NULL CHECK (wastage_cost >= 0),
    reason VARCHAR(120) NOT NULL,
    record_date DATE NOT NULL
);

CREATE INDEX idx_orders_customer ON orders(customer_id);
CREATE INDEX idx_orders_restaurant_date ON orders(restaurant_id, order_date);
CREATE INDEX idx_order_items_order ON order_items(order_id);
CREATE INDEX idx_order_items_menu_item ON order_items(menu_item_id);
CREATE INDEX idx_pricing_menu_effective ON pricing_history(menu_item_id, effective_from);
CREATE INDEX idx_wastage_restaurant_date ON wastage(restaurant_id, record_date);
